FROM n8nio/n8n:latest

USER root

# Instalamos Python y dependencias de sistema
RUN apk add --update --no-cache python3 py3-pip python3-dev build-base

# Instalamos las librerías de Python que necesitas para tu Fase 2
# Usamos --break-system-packages porque en Docker es seguro hacerlo
RUN pip3 install pymongo pandas databricks-sql-connector --break-system-packages

USER node